name: Demo Work
on: workflow_dispatch
jobs:
  print:
    runs-on: [self-hosted]
    steps:
      - name: Smena papki
        run: |
          pwd
          cd /home/ivan/github/java
          pwd
      - name: Git pull
        run: |
          pwd
          git pull
          
