name: Demo Work
on: workflow_dispatch
jobs:
  print:
    runs-on: [self-hosted]
    steps:
      - name: Print to console
        run: echo Hello GH Action!
      - name: Print a few lines
        run: |
          pwd
          ls -la
